### ISSUE TITLE
Push for Homey 2 not available

### ISSUE THREAD

**Issue by RuudSlot** [rhannink/org.hannink.prowl#1]
I used push at stable version Homey. Now new beta version but push not compatable. Amy idea for update?

**Comment by rhannink** [comment]
I have started porting the app to sdk2, but I am not a real programmer and I have limmited time. So I am working on it but can’t give you a deadline yet......

**Comment by Puffpiloot** [comment]
Same here since the update......feel naked....:-)

**Comment by rhannink** [comment]
I just published the new version 2 off the app to Athom. It has to be approved before it gets into the App Store. In the mean time you can install it from GitHub using the Athom-cli tools.

[https://github.com/rhannink/org.hannink.prowl](url)

Ledring is not implemented yet.......TODO

**Comment by rhannink** [comment]
It is already approved and in the App Store: [https://apps.athom.com/app/org.hannink.prowl](url)

**Comment by rhannink** [comment]
Please forget version 2.0.0 and wait for 2.0.1. Due to missing packages 2.0.0 is not working.
